version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jugo
      - MONGO_INITDB_ROOT_PASSWORD=pass
volumes:
  mongodata: