version: '3.8'

services:
  api:
    container_name: pet-machine_api
    restart: always
    build: ./api
    ports:
      - "8000:8000"
    volumes: 
      - ./api:/api
    links:
      - mongodb

  mongodb:
    container_name: pet-machine_mongo
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
      - ./mongo/db_init.js:/docker-entrypoint-initdb.d/db_init.js
